create table tb_client (id  bigserial not null, age int4, created_at TIMESTAMP WITHOUT TIME ZONE, email varchar(255), name varchar(255), updated_at TIMESTAMP WITHOUT TIME ZONE, primary key (id));
create table tb_guess (id  bigserial not null, created_at TIMESTAMP WITHOUT TIME ZONE, updated_at TIMESTAMP WITHOUT TIME ZONE, client_id int8, third_id int8, vice_id int8, winner_id int8, primary key (id));
create table tb_role (id  bigserial not null, authority varchar(255), primary key (id));
create table tb_team (id  bigserial not null, created_at TIMESTAMP WITHOUT TIME ZONE, img_url varchar(255), name varchar(255), updated_at TIMESTAMP WITHOUT TIME ZONE, primary key (id));
create table tb_user (id  bigserial not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
alter table tb_guess add constraint FK5rrijsl3pdpelsyl0fpvj21rp foreign key (client_id) references tb_client;
alter table tb_guess add constraint FKqm7jdst4ttbpfhrkkjdhnol1i foreign key (third_id) references tb_team;
alter table tb_guess add constraint FK7cgxiuv1t19vh23h1260753mi foreign key (vice_id) references tb_team;
alter table tb_guess add constraint FKmn2kby4g3wwb1byuhk9b4a6b4 foreign key (winner_id) references tb_team;
alter table tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Alex', 'Brown', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Maria', 'Green', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_role (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Qatar', 'Qatar' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Equador', 'Equador' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Senegal', 'Senegal' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Holanda', 'Holanda' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Inglaterra', 'Inglaterra' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Irã', 'Ira' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('EUA', 'EUA' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('País de Gales', 'Pais' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Argentina', 'Argentina' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Arábia Saudita', 'Arabia' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('México', 'Mexico' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Polônia', 'Polonia' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('França', 'Franca' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Dinamarca', 'Dinamarca' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Tunísia', 'Tunisia' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Austrália', 'Australia' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Espanha', 'Espanha' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Alemanha', 'Alemanha' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Japão', 'Japao' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Costa Rica', 'Costa' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Bélgica', 'Belgica' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Canadá', 'Canada' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Marrocos', 'Marrocos' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Croácia', 'Croacia' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Brasil', 'Brasil' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Sérvia', 'Servia' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Suíça', 'Suica' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Camarões', 'Camaroes' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Portugal', 'Portugal' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Gana', 'Gana' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Uruguai', 'Uruguai' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Coreia do Sul', 'Coreia' , NOW());
create table tb_client (id  bigserial not null, age int4, created_at TIMESTAMP WITHOUT TIME ZONE, email varchar(255), name varchar(255), updated_at TIMESTAMP WITHOUT TIME ZONE, primary key (id));
create table tb_guess (id  bigserial not null, created_at TIMESTAMP WITHOUT TIME ZONE, updated_at TIMESTAMP WITHOUT TIME ZONE, client_id int8, third_id int8, vice_id int8, winner_id int8, primary key (id));
create table tb_role (id  bigserial not null, authority varchar(255), primary key (id));
create table tb_team (id  bigserial not null, created_at TIMESTAMP WITHOUT TIME ZONE, img_url varchar(255), name varchar(255), updated_at TIMESTAMP WITHOUT TIME ZONE, primary key (id));
create table tb_user (id  bigserial not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
alter table tb_guess add constraint FK5rrijsl3pdpelsyl0fpvj21rp foreign key (client_id) references tb_client;
alter table tb_guess add constraint FKqm7jdst4ttbpfhrkkjdhnol1i foreign key (third_id) references tb_team;
alter table tb_guess add constraint FK7cgxiuv1t19vh23h1260753mi foreign key (vice_id) references tb_team;
alter table tb_guess add constraint FKmn2kby4g3wwb1byuhk9b4a6b4 foreign key (winner_id) references tb_team;
alter table tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Alex', 'Brown', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Maria', 'Green', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_role (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Qatar', 'Qatar' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Equador', 'Equador' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Senegal', 'Senegal' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Holanda', 'Holanda' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Inglaterra', 'Inglaterra' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Irã', 'Ira' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('EUA', 'EUA' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('País de Gales', 'Pais' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Argentina', 'Argentina' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Arábia Saudita', 'Arabia' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('México', 'Mexico' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Polônia', 'Polonia' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('França', 'Franca' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Dinamarca', 'Dinamarca' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Tunísia', 'Tunisia' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Austrália', 'Australia' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Espanha', 'Espanha' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Alemanha', 'Alemanha' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Japão', 'Japao' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Costa Rica', 'Costa' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Bélgica', 'Belgica' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Canadá', 'Canada' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Marrocos', 'Marrocos' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Croácia', 'Croacia' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Brasil', 'Brasil' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Sérvia', 'Servia' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Suíça', 'Suica' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Camarões', 'Camaroes' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Portugal', 'Portugal' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Gana', 'Gana' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Uruguai', 'Uruguai' , NOW());
INSERT INTO tb_team (name, img_url, created_At) VALUES ('Coreia do Sul', 'Coreia' , NOW());
